language: php

sudo: required

services:
  - docker

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

env:
  - BOULDER_HOST="http://127.0.0.1:4000"

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - ./test/.run-boulder.sh

install:
  - composer install
  - composer require satooshi/php-coveralls dev-master --dev
  - composer show --installed

script:
  - find -name "*.php" -not -path "./vendor/*" -print0 | xargs -n 1 -0 php -l
  - vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v
